### ISSUE TITLE
Addressing Linux and Mac support (Android Possibly)

### ISSUE THREAD

**Issue by UnknownAMD** [lily-snow-9/FNAF-Engine-Reborn#5]
## The Issue: 
- WinForms is exclusive to windows meaning you cannot use the engine on any other OS

### The Plan:
1. **Heavy Cleanup:** I will clean up the code base, which has become messy over a year of development, handling both logic and UI in a huge monolith of a script. To achieve this, I'll  split the functionality into multiple files and create types and classes everywhere possible without needing to change GameData.

2. **UI Redesign:** I'll rewrite the entire editor's UI using Avalonia, a cross-platform UI framework, making it not only look way better but also run on Linux and Mac.

3. **Runtime Renderer Redesign:** I'll consider rewriting the runtime renderer using either Avalonia or OpenTK because that also uses WinForms and its also a monolith of a script.

### The Structure:
The editor's UI script has become messy over time due to ages of development. While this approach has some advantages, it also requires significant rewriting. As part of the heavy cleanup, I'm basically gonna restructure the code base, making it more manageable and maintainable and less for a brain fuck for me and lily.

### Why do we need this?
There are several reasons for these changes:

1. **Cross-Platform Compatibility:** By making the engine compatible with different operating systems, including Linux, more people will be able to use it and it also means we can make an android version.

2. **Enhanced UI Experience:** The migration to Avalonia and the planned UI redesign will provide a more visually appealing and user-friendly interface, contributing to a better overall experience for everyone here.

### Rough Idea of the New UI:
The redesigned UI will be similar to a typical game engine.
Here's a rough idea of the changes:

- The UI will introduce a tab-based system, where each tab represents a window for a Game Component or a Project/Game, because there will be two sets of tabs.
- New UI will use a hierarchy for objects like Animatronics, Scripts, and other components (e.g., mini-games), create them using the right click context menu.
- For mini-games, there will be a separate 2D editor with a preview in the center, again like a typical engine.
- The editor window will have a 16:9 aspect ratio (responsive resolution), featuring the hierarchy on the left, the debug console at the bottom, and controls accessible from the menu bar on the right. or top (not sure yet)

lily i spent an hour writing this plz accept (i already started with cleaning up the monolith btw)

**Comment by lily-snow-9** [comment]
ok

**Comment by UnknownAMD** [comment]
this aged well
